
import { Component } from "react";
import { Link, withRouter } from "react-router-dom";




class Home extends Component {
    constructor(props) {
        super(props);
    this.state = {
            query: ""
        };
    }

    

    onChange() {
        console.log(this.state.query);
    }

        render() {
        return (<div>
            <div className="flex flex-col items-center justify-center mx-auto min-h-screen">
              <div>
                <title>Vision Homepage</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
              </div>
              <div className="">
                <h1 className="text-5xl font-lg font-mono leading-tight text-blue-400">
                  Vision: The Search Engine
                </h1>
              </div>
              <form className="my-20 w-2/5 border-blue-900 flex flex-col justify-center items-center">
                <input
                  className="border-4 border-blue-500 w-full px-7 py-3 shadow-sm focus:bg-gray-100 focus:border-blue-900 rounded-full mb-10"
                  type="text"
                  placeholder="Vision Search"
                  value={this.state.query}
                  onChange={(e) => this.setState({query: e.target.value})}
                //   onChange={(e) => onChange(e)}
                ></input>
                    <Link 
                    to={{
                        pathname: "/search",
                        state: {query: this.state.query} // your data array of objects
                    }}
                    >   
                  Search Now!
                </Link>
                <Link to="/request/crawl">Request Crawl</Link>
                {/* <button onClick={console.log(this.state.query)}>test button</button> */}
              </form>
            </div>
            </div>
            );
}
}


export default withRouter(Home);
